[tool.black]
line-length = 100
target-version = ["py311"]
include = "(tools/.*\\.py$)"

[tool.ruff]
line-length = 100
target-version = "py311"
src = ["tools"]

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP", "B", "N"]

[tool.mypy]
python_version = "3.11"
strict = false
warn_unused_configs = true
mypy_path = "tools"
files = ["tools"]

